<?php
/*
 * Modify profile menu link and redirect to home if no access
 */


/**
 * @param array $items
 */
function dm_profileguard_menu_alter(&$items)
{
    $items['user/%user']['access callback'] = '_dm_profileguard_check_access_for';
    $items['user/%user']['access arguments'] = array(1);
}

/**
 * @param \stdClass $requestedAccount
 * @return null
 */
function _dm_profileguard_check_access_for($requestedAccount)
{
    /** @var \stdClass $user */
    //global $user;
    $canViewProfile = false;

    if (!user_is_logged_in()) {
        //can only view profiles of coaches
        if (in_array('coach', $requestedAccount->roles)) {
            $canViewProfile = true;
        }
    } else {
        //for now can view all other profiles
        $canViewProfile = true;
    }

    if ($canViewProfile) {
        return true;
    }

    drupal_goto('<front>', [], 301);
    return true;
}
